In [3]:
import numpy

In [2]:
print(dir(numpy))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_CopyMode', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__git_version__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__

In [7]:
import numpy as np

In [4]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_CopyMode', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__git_version__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__

In [6]:
np.arange(18)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [7]:
np.arange(5,18)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

In [14]:
np.array([1,2,3,4,5,6,7,78,3])

array([ 1,  2,  3,  4,  5,  6,  7, 78,  3])

# 2D Array

In [18]:
np.array([[1,2,3,4],[1,2,4,5],[1,2,3,4],[1,2,3,4]])

array([[1, 2, 3, 4],
       [1, 2, 4, 5],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [19]:
np.array([[1,2,3,4],[1,2,3]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [21]:
a1 = np.array([[1,2,3,4],[1,2,3,4]])
print(a1)

[[1 2 3 4]
 [1 2 3 4]]


In [22]:
a1.shape

(2, 4)

In [23]:
a1.dtype

dtype('int32')

In [34]:
print(a1)
print(type(a1))
print(id(a1))

[[1. 2. 3. 4.]
 [1. 2. 3. 4.]]
<class 'numpy.ndarray'>
2748277896752


In [27]:
a1.itemsize


4

In [25]:
a2 = np.array([[1,2,3,4],[1,2,3,4]], dtype="int64")
print(a2)

[[1 2 3 4]
 [1 2 3 4]]


In [26]:
a2.dtype

dtype('int64')

In [28]:
a2.itemsize

8

In [30]:
a1 = np.array([[1,2,3,4],[1,2,3,4]],dtype='float64')

In [33]:
print(a1)
print(type(a1))
print(id(a1))

[[1. 2. 3. 4.]
 [1. 2. 3. 4.]]
<class 'numpy.ndarray'>
2748277896752


In [32]:
a1.itemsize

8

In [42]:
a1 = np.array([[1,2,3],[1,2,3]])

print(a1)

a2 = a1    # a1 and a2  Both take same refference  

print(a2)

a2[1,1] = 100


print()
print(a1)
print(a2)



[[1 2 3]
 [1 2 3]]
[[1 2 3]
 [1 2 3]]

[[  1   2   3]
 [  1 100   3]]
[[  1   2   3]
 [  1 100   3]]


In [43]:
a1 = np.array([[1,2,3],[1,2,3]])

print(a1)

a2 = a1.copy()    # a1 and a2  Both take different refference  

print(a2)

a2[1,1] = 100


print()
print(a1)
print(a2)

[[1 2 3]
 [1 2 3]]
[[1 2 3]
 [1 2 3]]

[[1 2 3]
 [1 2 3]]
[[  1   2   3]
 [  1 100   3]]


# Slicing

In [47]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])


In [48]:
arr.shape

(15,)

In [49]:
arr[:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [50]:
arr[2:]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [51]:
arr[:12]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [52]:
arr[5:7]

array([6, 7])

In [53]:
arr[-1:]

array([15])

In [54]:
arr[:-1]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [55]:
arr[np.newaxis,4:7]   # ek index cam hi print hota hai

array([[5, 6, 7]])

In [59]:
mat = arr.reshape(5,3)
print(mat)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [76]:
print(mat[:,:])

print()

print(mat[:])


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [79]:
print(mat[2:,:3])

print()

print(mat[2:,:2])

[[ 7  8  9]
 [10 11 12]
 [13 14 15]]

[[ 7  8]
 [10 11]
 [13 14]]


In [80]:
mat[np.newaxis,1:,:]

array([[[ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15]]])

# Sorting

In [88]:
mat.sort()   # it give sorted element in a list
print(mat)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [93]:
np.sort(mat)  # it give element in a array

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [90]:
a = np.array([2,4,1,4,2,5,2,4,44,1,4,12,23,1,])
print(a)

[ 2  4  1  4  2  5  2  4 44  1  4 12 23  1]


In [96]:
print(np.sort(a))    # ye original array ko sort nahi karta but list mai original array sort ho jata hai

print(a)  



[ 1  1  1  2  2  2  4  4  4  4  5 12 23 44]
[ 2  4  1  4  2  5  2  4 44  1  4 12 23  1]


In [100]:
%time np.sort(a, kind="mergesort")  # ye bhi original array ko sort nahi karta


CPU times: total: 0 ns
Wall time: 0 ns
[ 2  4  1  4  2  5  2  4 44  1  4 12 23  1]


In [101]:
%time np.sort(a, kind="quicksort")  # ye bhi original array ko sort nahi karta

CPU times: total: 0 ns
Wall time: 0 ns


array([ 1,  1,  1,  2,  2,  2,  4,  4,  4,  4,  5, 12, 23, 44])

In [102]:
%time np.sort(a, kind="heapsort")  # ye bhi original array ko sort nahi karta

CPU times: total: 0 ns
Wall time: 0 ns


array([ 1,  1,  1,  2,  2,  2,  4,  4,  4,  4,  5, 12, 23, 44])

In [104]:
b = np.array([[23,1,3,12,4,13],[43,1,31,34,13,32],[5,634,45,45,413,34]])
print(b)

[[ 23   1   3  12   4  13]
 [ 43   1  31  34  13  32]
 [  5 634  45  45 413  34]]


In [107]:
print(np.sort(b,axis=0))  # ye every colum ko short karenga 
print()
print(b)  # ye original array ko sort nahi karta

[[  5   1   3  12   4  13]
 [ 23   1  31  34  13  32]
 [ 43 634  45  45 413  34]]

[[ 23   1   3  12   4  13]
 [ 43   1  31  34  13  32]
 [  5 634  45  45 413  34]]


In [108]:
np.sort(b,axis=1)  # ye every row ko short karenga 

array([[  1,   3,   4,  12,  13,  23],
       [  1,  13,  31,  32,  34,  43],
       [  5,  34,  45,  45, 413, 634]])

# Airthmatic operation on matrix

In [110]:
print(b+b)
print()

print(b-b)
print()

print(b/b)
print()

print(b//b)
print()

print(b*b)
print()

print(b**b)
print()


[[  46    2    6   24    8   26]
 [  86    2   62   68   26   64]
 [  10 1268   90   90  826   68]]

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]

[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]

[[   529      1      9    144     16    169]
 [  1849      1    961   1156    169   1024]
 [    25 401956   2025   2025 170569   1156]]

[[-1276351769           1          27  -251658240         256 -1692154371]
 [  407106611           1 -2010103841           0 -1692154371           0]
 [       3125           0 -1714755555 -1714755555  -222567027           0]]



In [114]:
print(b)
print()
np.dot(b,b.transpose())

[[ 23   1   3  12   4  13]
 [ 43   1  31  34  13  32]
 [  5 634  45  45 413  34]]



array([[   868,   1959,   3518],
       [  1959,   5160,  10231],
       [  3518,  10231, 577756]])

In [115]:
a = np.array([[5,6],[5,9]])
b = np.array([[4,7],[8,9]])

np.cross(a,b)

array([ 11, -27])

In [117]:
print(a.sum())
print(b.sum())

25
28


# argsort argmin and argmax

In [5]:
a = np.array([1,2,23,12,354,1,23])
print(a)

[  1   2  23  12 354   1  23]


In [6]:
a.argsort()

array([0, 5, 1, 3, 2, 6, 4], dtype=int64)

In [7]:
a.argmax()

4

In [8]:
a.argmin()

0

# Empty array

In [10]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [11]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [13]:
np.empty(15)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [37]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


# Stacking of array

In [8]:
a = np.arange(5,101,5).reshape(4,5)
print(a)

print()

b = np.arange(4,81,4).reshape(4,5)
print(b)

[[  5  10  15  20  25]
 [ 30  35  40  45  50]
 [ 55  60  65  70  75]
 [ 80  85  90  95 100]]

[[ 4  8 12 16 20]
 [24 28 32 36 40]
 [44 48 52 56 60]
 [64 68 72 76 80]]


In [13]:
d = np.vstack((a,b))
print(d)

[[  5  10  15  20  25]
 [ 30  35  40  45  50]
 [ 55  60  65  70  75]
 [ 80  85  90  95 100]
 [  4   8  12  16  20]
 [ 24  28  32  36  40]
 [ 44  48  52  56  60]
 [ 64  68  72  76  80]]


In [10]:
c = np.hstack((a,b))
print(c)

[[  5  10  15  20  25   4   8  12  16  20]
 [ 30  35  40  45  50  24  28  32  36  40]
 [ 55  60  65  70  75  44  48  52  56  60]
 [ 80  85  90  95 100  64  68  72  76  80]]


In [11]:
np.hsplit(c,5)

[array([[ 5, 10],
        [30, 35],
        [55, 60],
        [80, 85]]),
 array([[15, 20],
        [40, 45],
        [65, 70],
        [90, 95]]),
 array([[ 25,   4],
        [ 50,  24],
        [ 75,  44],
        [100,  64]]),
 array([[ 8, 12],
        [28, 32],
        [48, 52],
        [68, 72]]),
 array([[16, 20],
        [36, 40],
        [56, 60],
        [76, 80]])]

In [14]:
d

array([[  5,  10,  15,  20,  25],
       [ 30,  35,  40,  45,  50],
       [ 55,  60,  65,  70,  75],
       [ 80,  85,  90,  95, 100],
       [  4,   8,  12,  16,  20],
       [ 24,  28,  32,  36,  40],
       [ 44,  48,  52,  56,  60],
       [ 64,  68,  72,  76,  80]])

In [15]:
np.vsplit(d,8)

[array([[ 5, 10, 15, 20, 25]]),
 array([[30, 35, 40, 45, 50]]),
 array([[55, 60, 65, 70, 75]]),
 array([[ 80,  85,  90,  95, 100]]),
 array([[ 4,  8, 12, 16, 20]]),
 array([[24, 28, 32, 36, 40]]),
 array([[44, 48, 52, 56, 60]]),
 array([[64, 68, 72, 76, 80]])]

In [16]:
np.vsplit(d,4)

[array([[ 5, 10, 15, 20, 25],
        [30, 35, 40, 45, 50]]),
 array([[ 55,  60,  65,  70,  75],
        [ 80,  85,  90,  95, 100]]),
 array([[ 4,  8, 12, 16, 20],
        [24, 28, 32, 36, 40]]),
 array([[44, 48, 52, 56, 60],
        [64, 68, 72, 76, 80]])]

# Iteration

In [29]:
a = np.arange(30).reshape(5,6)
print(a)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


In [30]:
print(a.flatten())

print()

print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


In [31]:
for i in a.flatten():
    print(i, end=" ")

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 

In [32]:
for i in a:
    print(i)

[0 1 2 3 4 5]
[ 6  7  8  9 10 11]
[12 13 14 15 16 17]
[18 19 20 21 22 23]
[24 25 26 27 28 29]


In [33]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [34]:
for row in a:
    for cell in row:
        print(cell)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29


In [44]:
for i in a:
    print(i)
    

print()

print(np.nditer(a))

print()

for i in np.nditer(a, order="C"):  # c styling
    print(i, end=" ")

[0 1 2 3 4 5]
[ 6  7  8  9 10 11]
[12 13 14 15 16 17]
[18 19 20 21 22 23]
[24 25 26 27 28 29]


0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 

In [45]:
for i in a:
    print(i)
    

print()

print(np.nditer(a))

print()

for i in np.nditer(a, order="F"):  # fortan styling
    print(i, end=" ")

[0 1 2 3 4 5]
[ 6  7  8  9 10 11]
[12 13 14 15 16 17]
[18 19 20 21 22 23]
[24 25 26 27 28 29]


0 6 12 18 24 1 7 13 19 25 2 8 14 20 26 3 9 15 21 27 4 10 16 22 28 5 11 17 23 29 

In [48]:
for i in a:
    print(i)
    

print()

print(np.nditer(a))

print()

for i in np.nditer(a, order="C", flags=['external_loop']):  # External Looping
    print(i)

[0 1 2 3 4 5]
[ 6  7  8  9 10 11]
[12 13 14 15 16 17]
[18 19 20 21 22 23]
[24 25 26 27 28 29]


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [49]:
for i in a:
    print(i)
    

print()

print(np.nditer(a))

print()

for i in np.nditer(a, order="F", flags=['external_loop']):  # External Looping
    print(i)

[0 1 2 3 4 5]
[ 6  7  8  9 10 11]
[12 13 14 15 16 17]
[18 19 20 21 22 23]
[24 25 26 27 28 29]


[ 0  6 12 18 24]
[ 1  7 13 19 25]
[ 2  8 14 20 26]
[ 3  9 15 21 27]
[ 4 10 16 22 28]
[ 5 11 17 23 29]


In [63]:
a = np.arange(12).reshape(3,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [67]:
for x in np.nditer(a, op_flags=['readwrite']):
    x[...] = x*x  # change all value during iteration
    
print(a)

[[          0           1       65536    43046721]
 [          0 -2030932031  -683606016 -1526366847]
 [          0  -501334399  1874919424   772479681]]


In [69]:
np.linspace(0, 10, num=5)  # 0 se  10 ke bich ke 5 number denga

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [70]:
np.linspace(0, 20, num=5)

array([ 0.,  5., 10., 15., 20.])

In [73]:
x = np.array([[1,2],[3,4]])
y = np.array([[4,5]])

print()
print(x)
print(y)
print()

np.concatenate((x,y), axis=0)



[[1 2]
 [3 4]]
[[4 5]]



array([[1, 2],
       [3, 4],
       [4, 5]])

In [75]:
x = np.array([[1,2],[3,4]])
y = np.array([[4],[5]])

print()
print(x)
print(y)
print()

np.concatenate((x,y), axis=1)



[[1 2]
 [3 4]]
[[4]
 [5]]



array([[1, 2, 4],
       [3, 4, 5]])

# Sorting and Retrieving Numpy arrays

In [78]:
a = np.arange(1,100,4)


In [81]:
a

array([ 1,  5,  9, 13, 17, 21, 25, 29, 33, 37, 41, 45, 49, 53, 57, 61, 65,
       69, 73, 77, 81, 85, 89, 93, 97])

In [82]:
np.save("1d_array",a)   # file created of  this name

In [83]:
np.load("1d_array.npy")

array([ 1,  5,  9, 13, 17, 21, 25, 29, 33, 37, 41, 45, 49, 53, 57, 61, 65,
       69, 73, 77, 81, 85, 89, 93, 97])

In [85]:
arr = np.arange(1000000).reshape(200000,5)
print(arr)

[[     0      1      2      3      4]
 [     5      6      7      8      9]
 [    10     11     12     13     14]
 ...
 [999985 999986 999987 999988 999989]
 [999990 999991 999992 999993 999994]
 [999995 999996 999997 999998 999999]]


In [86]:
np.savez("2d_array", arr)

In [87]:
np.savetxt("sample.txt",arr)

In [88]:
np.savetxt("sample.csv",arr,delimiter=",")